channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatomic==2026.03.30.mta1
  - pip
  - pip:
    - metatrain>=2026.3.1
    - chemiscope==1.0.3
    - matplotlib
    - atomistic-cookbook-utils >=0.1,<0.2
