channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - matplotlib
  - pip:
    - ase>=3.28
    - metatrain<2026.3 # Because of writing of mtt::aux::cutoff-stats in the XYZ file
    - atomistic-cookbook-utils >=0.1,<0.2
