# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools we need
build:
  os: ubuntu-22.04
  apt_packages:
    - cmake
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/src/conf.py

# Declare the Python requirements required to build the docs
python:
   install:
   - method: pip
     path: .
   - requirements: docs/requirements.txt
   - requirements: docs/requirements-prebuilt.txt

