channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - tqdm
  - matplotlib
  - pandas
  - chemiscope
  - pip:
    - ase>=3.27
    - upet>=0.2.3
    - "warp-lang==1.13.0"
    - ipi>=3.2.0
    - metatomic-torch
    - metatomic-ase
    - metatrain
    - vesin>=0.4.2
    - atomistic-cookbook-utils >=0.1,<0.2