channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - tqdm
  - matplotlib
  - pandas
  - pip:
    - ase>=3.27
    - upet>=0.2.1
    - ipi>=3.1.8,<4
    - metatomic-torch<=0.1.8
    - metatrain
    - vesin>=0.4.2
