seed: 42

architecture:
  name: pet

  training:
    batch_size: 16
    num_epochs: 2000
    num_epochs_warmup: 10
    learning_rate: 1e-4
    

# this needs specifying based on the specific dataset
training_set:
  systems: 
    read_from: "data/ethanol_train.xyz"  # path to the finetuning dataset
    length_unit: angstrom
  targets:
    energy:
      key: "energy-corrected"  # name of the target value
      unit: "eV"

validation_set:
  systems: 
    read_from: "data/ethanol_val.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy-corrected"
      unit: "eV"

test_set:
  systems: 
    read_from: "data/ethanol_test.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy-corrected"
      unit: "eV"
