seed: 42

architecture:
  name: pet

  training:
    batch_size: 32
    num_epochs: 1000
    learning_rate: 1e-4
    

# this needs specifying based on the specific dataset
training_set:
  systems: 
    read_from: "data/ethanol_train.xyz"  # path to the dataset
    length_unit: angstrom
  targets:
    energy:
      key: "energy"  # name of the target value
      unit: "eV"

validation_set:
  systems: 
    read_from: "data/ethanol_val.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy"
      unit: "eV"

test_set:
  systems: 
    read_from: "data/ethanol_test.xyz"
    length_unit: angstrom
  targets:
    energy:
      key: "energy"
      unit: "eV"
