channels:
  - abmazitov
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatensor=*=cpu*nompi*
  - pip
  - pip:
    - ase
    - chemiscope>=0.8
    - ipi>=3.1.5
    - metatensor-torch<0.8
    - metatensor-operations
    - matplotlib
    - torch-pme
    - metatomic  
    - vesin[torch]
