channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase
    - chemiscope>=0.7
    - metatensor-torch<0.7
    - metatensor-operations
    - matplotlib
    - torch-pme<0.3
    - vesin[torch]
