channels:
  - abmazitov
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatensor=*=cpu*nompi*
  - pip
  - pip:
    - ase
    - chemiscope>=0.8.5
    - ipi
    - metatensor-torch<0.8
    - metatensor-operations
    - matplotlib
    - torch-pme==0.3.0
    - vesin[torch]==0.3.2
