channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase
    - chemiscope>=0.7
    - ipi
    - metatensor-torch<0.8
    - metatensor-operations
    - matplotlib
    - torch-pme
    - vesin[torch]
