channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatomic
  - pip
  - pip:
    - ase
    - chemiscope>=1.0
    - ipi>=3.1.5
    - metatensor-torch>=0.8,<0.9
    - metatensor-operations
    - matplotlib
    - metatomic-torch
    - vesin>=0.5.4
    - vesin-torch>=0.5.4
    - torch-pme>=0.3.1,<0.4
