channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gfortran
  - make
  - pip:
    - numpy
    - ase==3.22.1
    - chemiscope>=0.8
    - ipi @ git+https://github.com/i-pi/i-pi.git@fix_socket_conda
    - matplotlib
