dependencies:
  - python=3.11
  - pip
  - pip:
    - ase
    - equisolve @ git+https://github.com/lab-cosmo/equisolve.git@c858bedef4b2799eb445e4c92535ee387224089a
    - matplotlib
    - metatensor
    - rascaline @ git+https://github.com/Luthaf/rascaline@ca957642f512e141c7570e987aadc05c7ac71983
