channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rust >=1.65
  - pip:
    - ase==3.22.1
    - equisolve @ git+https://github.com/lab-cosmo/equisolve.git@c858bedef4b2799eb445e4c92535ee387224089a
    - matplotlib
    - metatensor
    - metatensor-core==0.1.11
    - featomic
