name: chemiscope_auto
dependencies:
  - python=3.11
  - pip
  - rust
  - pip:
    - ase==3.22.1
    - matplotlib
    - scikit-learn
    - chemiscope @ git+https://github.com/lab-cosmo/chemiscope@sphinx-gallery
    - load_atoms
    - umap-learn
    - rascaline @ git+https://github.com/Luthaf/rascaline@5c2a79838bda0a52d0fde2fbe65941f4792c4cae
    - metatensor
    - mace-torch
    - requests
    - tqdm
