channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatomic=2025.09.10.mta3
  - pip
  - pip:
    - ase
    - upet>=0.2.1
    - ipi>=3.1.8
    - chemiscope>=1.0
    - matplotlib
    - metatomic-torch<=0.1.8
    - vesin>=0.4.2
    - requests
