channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatomic=2025.09.10.mta3
  - pip
  - pip:
    - ase
    - upet>=0.2.3
    - ipi>=3.2.0
    - chemiscope>=1.0
    - matplotlib
    - vesin>=0.4.2
    - atomistic-cookbook-utils >=0.1,<0.2
