channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - ase>=3.23
    - ipi==3.1.5
    - vesin[torch]>=0.3.2,<0.4
    - flashmd>=0.2.2
    - metatrain  
    - chemiscope>=0.8.5,<0.9 
    - matplotlib
