channels:
  - plumed/label/ipi-demo
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gfortran
  - make
  - git
  - plumed
  - lammps
  - py-plumed  
  - pip:
    - ase==3.22.1
    - chemiscope
    - ipi
    - matplotlib
variables:
  PYTHONPATH: 
  PLUMED_KERNEL:
