channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - plumed-metatomic
  - py-plumed-metatomic
  - pip:
    - ase
    - numpy
    - chemiscope
    - metatensor[torch]
    - featomic-torch
variables:
  PLUMED_KERNEL:
