channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - plumed-metatomic
  - py-plumed-metatomic
  - matplotlib
  - pip:
    - ase
    - numpy
    - chemiscope
    - torch
    - metatensor[torch]
    - featomic-torch
variables:
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
  PLUMED_KERNEL:
