channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - lammps  
  - pip:
    - ase==3.22.1
    - chemiscope>=0.7
    - git+https://github.com/i-pi/i-pi.git@main
    - matplotlib
    - skmatter
