channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - tqdm
  - matplotlib
  - pip:
    - ase>=3.28
    - upet>=0.2.5
    - metatrain
    - chemiscope
    - atomistic-cookbook-utils >=0.1,<0.2
