channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - tqdm
  - matplotlib
  - pip:
    - upet
    - ase>=3.28
    - git+https://github.com/metatensor/metatrain.git@new_dos_loss
    - atomistic-cookbook-utils >=0.1,<0.2
