channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - tqdm
  - matplotlib
  - pip:
    - git+https://github.com/lab-cosmo/upet.git@dos2
    - ase>=3.28
    - git+https://github.com/metatensor/metatrain.git@main
    - atomistic-cookbook-utils >=0.1,<0.2
