channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rust >=1.65
  - pip:
    - ase==3.22.1
    - matplotlib
    - rascaline @ git+https://github.com/Luthaf/rascaline@5c2a79838bda0a52d0fde2fbe65941f4792c4cae
    - skmatter
