channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase
    - chemiscope>=0.7
    - ipi
    - featomic-torch<0.7,>0.6
    - metatensor-torch<0.8
    - metatensor-operations
    - matplotlib
