channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rust >=1.65
  - pip:
    - ase<3.23
    - chemiscope>=0.7
    - matplotlib
    - metatensor
    - featomic
    - scikit-learn
    - skmatter>=0.3
