channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase<3.23
    - atomistic-cookbook-utils>=0.1,<0.2
    - chemiscope>=1.0
    - matplotlib
    - metatensor
    - featomic
    - scikit-learn
    - skmatter>=0.3
