channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - lammps  
  - pip:
    - ase==3.22.1
    - ipi  
    - chemiscope @ git+https://github.com/lab-cosmo/chemiscope@sphinx-gallery
    - matplotlib
    - skmatter
