name: water-md
channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - lammps-metatomic=2025.09.10.mta3
  - pip
  - pip:
    - upet>=0.2.4
    - chemiscope==1.0.3
    - matplotlib
    - atomistic-cookbook-utils >=0.1,<0.2
