channels:
  - conda-forge
dependencies:
  - python>=3.11
  - graphviz
  - pyscf=2.3.0
  - rust=1.88.*
  - pip
  - pip:
      - pyscfad @ git+https://github.com/fishjojo/pyscfad.git@ml#egg=pyscfad
      - ase==3.22.1
      - seekpath
      - requests
      - lightning
      - xitorch
      - keras_core
      - tensorboard
      - torchviz
      - mlelec @ git+https://github.com/curiosity54/mlelec.git@tutorial_periodic#egg=mlelec
