channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - graphviz
  - pyscf=2.3.0
  - rust>=1.65
  - pip:
      - pyscfad @ git+https://github.com/fishjojo/pyscfad.git@ml#egg=pyscfad
      - ase==3.22.1
      - seekpath
      - requests
      - metatensor==0.2.0
      - metatensor-core==0.1.12
      - metatensor-learn==0.3.1
      - metatensor-operations==0.3.2
      - metatensor-torch==0.7.2
      - --extra-index-url https://download.pytorch.org/whl/cpu 
      - rascaline-torch @ git+https://github.com/luthaf/rascaline@3450bc4d609aee87ab73648b059536baa97d15ac#subdirectory=python/rascaline-torch
      - lightning
      - xitorch
      - keras_core
      - tensorboard
      - torchviz
      - mlelec @ git+https://github.com/curiosity54/mlelec.git@tutorial_periodic#egg=mlelec
