channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - graphviz
  - pyscf=2.3.0
  - rust>=1.65
  - pip:
      - pyscfad @ git+https://github.com/fishjojo/pyscfad.git@ml#egg=pyscfad
      - ase==3.22.1
      - seekpath
      - requests
      # metatensor packages are pinned for consistency with the rascaline version required by the version of mlelec used in this tutorial
      - metatensor-core==0.1.11
      - metatensor-learn==0.3.0
      - metatensor-operations==0.3.0
      - metatensor-torch==0.6.3
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - lightning
      - xitorch
      - keras_core
      - tensorboard
      - torchviz
      - mlelec @ git+https://github.com/curiosity54/mlelec.git@tutorial_periodic#egg=mlelec
