# Lint tests run on PR
# but should not run after push to main because reporting
# these after push is meaningless to the building of the package
name: Lint

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # run every Monday at 8am UTC

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install tox

    - name: Test Lint
      run: tox -e lint
