# Lint tests run on PR
# but should not run after push to main because reporting
# these after push is meaningless to the building of the package
name: Lint

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # run every Monday at 8am UTC

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: install dependencies
      run: pip install nox docutils

    - name: test lint
      run: nox -e lint

    - name: Audit for large files
      uses: HaoZeke/large-file-auditor@v0.1.0
      with:
        file-size-threshold: "1M"
