channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase
    - git+https://github.com/metatensor/metatrain.git#egg=metatrain[soap-bpnn]
    - metatensor>=0.2,<0.3
    - matplotlib
    - chemiscope
    - featomic
